// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ggmaidbbyiuuzwyqtqri.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdnbWFpZGJieWl1dXp3eXF0cXJpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzgwOTEzMTgsImV4cCI6MjA1MzY2NzMxOH0.d8oEEG8XmbCvE6ZATSisimL0gFI73BLnd6v8G8eV7lI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);